name: Build and Upload APK

on:
  push:
    branches: [ main, flutterflow ]
  pull_request:
    branches: [ main, flutterflow ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Verify Project Structure
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Checking for pubspec.yaml:"
          find . -name "pubspec.yaml"

      - name: Cache Flutter packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            !~/.pub-cache/hosted/pub.dev/cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Install Dependencies
        run: |
          flutter clean
          flutter pub get

      # Удалён шаг тестов:
      # - name: Run Tests
      #   run: flutter test

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Compress APKs
        run: zip -r release-apks.zip build/app/outputs/flutter-apk/

      - name: Upload APK Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-apks
          path: release-apks.zip
