name: Build and Upload APK

on:
  push:
    branches: [ flutterflow ]
  pull_request:
    branches: [ flutterflow ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Берём код из ветки flutterflow
      - name: Checkout flutterflow
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: flutterflow

      # 2. Проверка структуры
      - name: Show files
        run: |
          echo "Root folder:"
          pwd
          ls -la

      # 3. Ставим Java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      # 4. Ставим Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'

      # 5. Сборка (переход в папку, если pubspec.yaml НЕ в корне)
      - name: Build APK
        run: |
          cd ./   # Если pubspec.yaml в корне ветки flutterflow, оставьте так
          # ИЛИ если pubspec.yaml в подпапке "flutterflow", замените на:
          # cd flutterflow
          flutter clean
          flutter pub get
          flutter build apk --release --split-per-abi

      # 6. Архив APK
      - name: Compress APKs
        run: |
          cd ./  # та же папка, где .build/app/outputs
          zip -r release-apks.zip build/app/outputs/flutter-apk/

      # 7. Загрузка артефактов
      - name: Upload APK Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-apks
          path: release-apks.zip
